excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://TheLegendOfAc3513.github.io
title: TheLegendOfAc3513
tagline: Blog of everyday life
description: I am 22 I live in Salem, Oregon, United State Of America. My dream is to open in to the hearts of others and show them that there is always a better way, and there is a othere ways to fight for what you believe in and there is others out here to help and love you just the way you are. Because I have delt with hard and non hard things, I am also just going to start bloging so I can get some things of my chest as well.
paginate: 5